import "./globals.css";
import "./fonts.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

export const metadata = {
  title: "Not Another Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#5D6771] text-white">
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
